spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:20010/security?serverTimezone=Asia/Seoul
        username: security
        password: dev
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
    port: 8081
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true

