spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:23306/security?serverTimezone=Asia/Seoul
        username: security
        password: ddev
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: 384012344549-voa6ce8iii4kfv5cu056o71nvu9pkjq9.apps.googleusercontent.com
                        client-secret: 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
                        scope:
                            - email
                            - profile
                    naver:
                        client-id: wtp3IG8_mpaWdIEyywmd
                        client-secret: EVUZwRuOn4
                        scope:
                            - name
                            - email
                        client-name: Naver
                        authorization-grant-type: authorization_code
                        redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
                provider:
                    naver:
                        authorization-uri: https://nid.naver.com/oauth2.0/authorize
                        token-uri: https://nid.naver.com/oauth2.0/token
                        user-info-uri: https://openapi.naver.com/v1/nid/me
                        user-name-attribute: response
server:
    port: 8081
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true

